name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: melvinmv02
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237C3AED%26color_dots=%23161B22%2C%23312E81%2C%234C1D95%2C%236D28D9%2C%23A78BFA
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
          commit_message: Update contribution snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
